### ISSUE TITLE
Move datetimeR functions to nolar

### ISSUE THREAD

**Issue by alexilliamson** [nola-r/nolar#1]
datetimeR was developed as a simple, standalone package, but we would like to move those functions into the nolar package and get rid of the datetimeR package.  

https://github.com/nola-r/datetimeR

**Comment by alexilliamson** [comment]
For context, at the time that datetimeR was created, we were planning on creating and maintaining multiple smaller packages.  However, we recently decided to put all OPA code in the same place (this nolar package).  So we thought that a good first step would be gathering all the code that has already been written into this repo.

**Comment by TheStatsHouse** [comment]
Made a pull request with the uploaded files (http://bit.ly/2xRvGAg)

**Comment by alexilliamson** [comment]
#3 One minor change before we merge the pull request
